services:
  ircd:
    image: ergochat/ergo:latest
    container_name: ironcord-ircd
    ports:
      - "6667:6667"
      - "6697:6697"
    volumes:
      - ./ergo.conf:/ircd/default.yaml:ro
    restart: unless-stopped
